before_script:
  - docker info
  - '[ -d tmp ] || mkdir tmp'
  - git clone https://github.com/OSC/ondemand-packaging.git tmp/ondemand-packaging
  - cp /systems/osc_certs/gpg/ondemand/.gpgpass $CI_PROJECT_DIR/tmp/ondemand-packaging/
  - cp /systems/osc_certs/gpg/ondemand/ondemand.sec $CI_PROJECT_DIR/tmp/ondemand-packaging/
  - '[ "x$CI_COMMIT_TAG" = "x" ] && export CI_COMMIT_TAG=$(git describe --tags --abbrev=0)'
stages:
  - build
#  - deploy

variables:
  GIT_STRATEGY: clone

rpm-build-el7:
  stage: build
  only:
    #- tags
    - external_pull_requests
  except:
    - branches
  script:
    - ./tmp/ondemand-packaging/build.sh -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output -V $CI_COMMIT_TAG -u -v -C -d el7 $CI_PROJECT_DIR/packaging/rpm
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

rpm-build-el8:
  stage: build
  only:
    #- tags
    - external_pull_requests
  except:
    - branches
  script:
    - ./tmp/ondemand-packaging/build.sh -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output -V $CI_COMMIT_TAG -u -v -C -d el8 $CI_PROJECT_DIR/packaging/rpm
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

#package-deploy:
#  stage: deploy
#  only:
#    - tags
#  script:
#    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c main ./tmp/output/*
