---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.4.0

executors:
  # Whenever the Go version is updated here, .promu.yml should
  # also be updated.
  golang:
    docker:
    - image: circleci/golang:1.13

jobs:
  test:
    executor: golang
    steps:
    - prometheus/setup_environment
    - run: make
    - prometheus/store_artifact:
        file: ondemand_exporter
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run: make promu
    - run: promu crossbuild -v
    - persist_to_workspace:
        root: .
        paths:
        - .build
    - store_artifacts:
        path: .build
        destination: /build
  release:
    executor: golang
    steps:
    - prometheus/setup_build_environment
    - run: promu crossbuild tarballs
    - run: promu checksum .tarballs
    - run: promu release .tarballs
    - store_artifacts:
        destination: releases
        path: .tarballs
workflows:
  version: 2
  ondemand_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        filters:
          tags:
            only: /.*/
    - release:
        context: org-context
        requires:
        - test
        - build
        filters:
          tags:
            only: /^([0-9]).*/
          branches:
            ignore: /.*/
