---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.11.0
  codecov: codecov/codecov@3.2.0

executors:
  # Whenever the Go version is updated here, .promu.yml should
  # also be updated.
  golang:
    docker:
    - image: circleci/golang:1.17

jobs:
  test:
    executor: golang
    steps:
    - prometheus/setup_environment
    - run: make
    - run: make coverage
    - codecov/upload:
        file: coverage.txt
    - prometheus/store_artifact:
        file: ondemand_exporter
workflows:
  version: 2
  ondemand_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        filters:
          tags:
            only: /.*/
    - prometheus/publish_release:
        context: org-context
        docker_hub_organization: ''
        quay_io_organization: ''
        requires:
        - test
        - prometheus/build
        filters:
          tags:
            only: /^v([0-9]).*/
          branches:
            ignore: /.*/
