{
 "title": "OnDemand",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(ondemand_active_puns, environment)"
   },
   {
    "name": "instance",
    "query": "label_values(ondemand_active_puns{environment=~\"$environment\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "OnDemand Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ondemand_active_puns{environment=~\"$environment\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active PUNs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ondemand_active_puns{environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ondemand_unique_client_connections{environment=~\"$environment\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ondemand_unique_websocket_clients{environment=~\"$environment\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "OnDemand Passenger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Passenger App Counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ondemand_passenger_app_count{environment=~\"$environment\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - {{app}}"
      }
     ]
    },
    {
     "title": "Passenger App CPU %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "ondemand_passenger_app_cpu_percent{environment=~\"$environment\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - {{app}}"
      }
     ]
    },
    {
     "title": "Passenger App Memory %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ondemand_passenger_app_real_memory_bytes{environment=~\"$environment\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - {{app}}"
      }
     ]
    },
    {
     "title": "Passenger App Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "Requests rate" }
     ],
     "targets": [
      {
       "expr": "irate(ondemand_passenger_app_requests_total{environment=~\"$environment\", instance=~\"$instance\"}[15m])",
       "legendFormat": "{{instance}} - {{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OnDemand Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apache Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ondemand_unique_client_connections{environment=~\"$environment\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - client connections"
      },
      {
       "expr": "ondemand_unique_websocket_clients{environment=~\"$environment\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - websocket connections"
      }
     ]
    }
   ]
  },
  {
   "title": "OnDemand Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "OnDemand Apps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ondemand_node_apps{environment=~\"$environment\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - NodeJS"
      },
      {
       "expr": "ondemand_rack_apps{environment=~\"$environment\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - Rack"
      }
     ]
    }
   ]
  },
  {
   "title": "OnDemand PUN Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "OnDemand PUN CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percentunit", "label": "% CPU" }
     ],
     "targets": [
      {
       "expr": "rate(ondemand_pun_cpu_time{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "OnDemand PUN Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "percent", "label": "% Memory" }
     ],
     "targets": [
      {
       "expr": "ondemand_pun_memory_percent{environment=~\"$environment\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}